export const GIPHY_FETCH_DATA_EFFECT = 'GIPHY_FETCH_DATA_EFFECT';
export const GIPHY_SEARCH_DATA_EFFECT = 'GIPHY_SEARCH_DATA_EFFECT';

export const GIPHY_SET_APPEND_DATA_STATE = 'GIPHY_SET_APPEND_DATA_STATE';
export const GIPHY_SET_LOADING_FULL_STATE = 'GIPHY_SET_LOADING_FULL_STATE';
export const GIPHY_SET_LOADING_SCROLL_STATE = 'GIPHY_SET_LOADING_SCROLL_STATE';