name: Deploy on AWS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 

      - name: Node Setup ${{ matrix.node-version }}
        uses: actions/setup-node@v2    
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy app build to S3 bucket (Main)
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync ./build s3://chirag-giphy-bucket --delete    